import Link from 'next/link';

export const metadata = {
  title: 'Privacy Policy | ADchaser',
  description: 'Privacy Policy for ADchaser – how we collect, use, and protect your data.',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
        <Link
          href="/"
          className="mb-8 inline-flex items-center text-sm font-medium text-zinc-400 transition hover:text-emerald-400"
        >
          ← Back to ADchaser
        </Link>
        <article className="prose prose-invert prose-slate max-w-none">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Privacy Policy</h1>
          <p className="text-sm text-zinc-400">Last updated: [Date]</p>

          <p>
            ADchaser (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) respects your privacy. This policy describes how we
            collect, use, and protect your information when you use our Service.
          </p>

          <h2>1. Information We Collect</h2>
          <p>We collect information you provide and data generated by your use of the product.</p>
          <ul>
            <li>
              <strong>Account data:</strong> When you sign up, we receive identity and contact
              information (e.g., email, name) from our authentication provider (Clerk). We use this
              to manage your account and provide the Service.
            </li>
            <li>
              <strong>Usage data:</strong> We store your saved ads and preferences (e.g., in our
              database) so we can display your vault and enforce plan limits.
            </li>
            <li>
              <strong>Payment data:</strong> When you subscribe, payment and billing information is
              processed by Stripe. We do not store full card numbers; we store subscription status
              and, where applicable, a Stripe customer identifier to support billing and the
              customer portal.
            </li>
          </ul>

          <h2>2. Cookies and Similar Technologies</h2>
          <p>
            We use cookies and similar technologies to keep you signed in, remember preferences,
            and operate the site. Our authentication provider (Clerk) and our hosting/analytics
            stack may set cookies. You can control cookies through your browser settings; disabling
            them may limit some features (e.g., staying logged in).
          </p>

          <h2>3. How We Use Your Information</h2>
          <p>We use the information we collect to:</p>
          <ul>
            <li>Provide, maintain, and improve the Service.</li>
            <li>Authenticate you and manage your account (via Clerk).</li>
            <li>Process payments and manage subscriptions (via Stripe).</li>
            <li>Enforce our Terms and plan limits (e.g., free vs. Pro).</li>
            <li>Respond to support requests and communicate with you (e.g., at [Contact Email]).</li>
            <li>Comply with legal obligations and protect our rights.</li>
          </ul>

          <h2>4. Data Sharing and Third Parties</h2>
          <p>
            We do not sell your personal data. We share data only as needed to run the Service:
          </p>
          <ul>
            <li>
              <strong>Clerk:</strong> Authentication and account management; they process data per
              their privacy policy.
            </li>
            <li>
              <strong>Stripe:</strong> Payment processing and billing; they process data per their
              privacy policy.
            </li>
            <li>
              <strong>Hosting/databases:</strong> Our infrastructure providers (e.g., Vercel,
              Supabase) store and process data as necessary to deliver the Service.
            </li>
          </ul>
          <p>
            We may disclose information if required by law or to protect our rights, safety, or
            property.
          </p>

          <h2>5. Data Retention and Security</h2>
          <p>
            We retain your data for as long as your account is active or as needed to provide the
            Service and comply with law. We use industry-standard measures to protect your data;
            no system is completely secure, and we cannot guarantee absolute security.
          </p>

          <h2>6. Your Rights</h2>
          <p>
            Depending on where you live, you may have rights to access, correct, delete, or port
            your data, or to object to or restrict certain processing. To exercise these rights or
            ask questions, contact us at [Contact Email]. You can also manage account and payment
            options through the Service (e.g., Stripe customer portal for billing).
          </p>

          <h2>7. Children</h2>
          <p>
            The Service is not intended for users under 18. We do not knowingly collect personal
            information from children; if you believe we have, please contact us at [Contact
            Email].
          </p>

          <h2>8. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. We will post the updated policy on
            this page and update the &quot;Last updated&quot; date. Continued use of the Service after
            changes constitutes acceptance. We may notify you of material changes via email or
            in-app notice where appropriate.
          </p>

          <h2>9. Contact</h2>
          <p>
            For privacy-related questions or requests, contact us at [Contact Email].
          </p>
        </article>
      </div>
    </div>
  );
}
